"""Add image path in Card

Revision ID: e4157ed5e0b3
Revises: 4b4f088f95ff
Create Date: 2025-12-23 11:11:05.003480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4157ed5e0b3'
down_revision = '4b4f088f95ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
